# Generated by Django 5.1.15 on 2026-08-05 00:52

import apps.billing.models
import apps.billing.storage
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("matters", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Attribué à l'émission (séquence sans trou).",
                        max_length=32,
                        verbose_name="numéro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "Impayée"),
                            ("cancelled", "Annulée"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "issued_at",
                    models.DateField(blank=True, null=True, verbose_name="date d'émission"),
                ),
                ("due_at", models.DateField(blank=True, null=True, verbose_name="échéance")),
                ("paid_at", models.DateField(blank=True, null=True, verbose_name="payée le")),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="devise")),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="taux de TVA (%)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total HT",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="montant TVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total TTC",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes / mentions")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        storage=apps.billing.storage.PrivateInvoiceStorage(),
                        upload_to=apps.billing.models.invoice_pdf_upload_to,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clients.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="matters.matter",
                        verbose_name="dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture",
                "verbose_name_plural": "factures",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("description", models.CharField(max_length=500, verbose_name="description")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="montant",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="devise")),
                ("incurred_on", models.DateField(verbose_name="date")),
                ("is_billable", models.BooleanField(default=True, verbose_name="facturable")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="matters.matter",
                        verbose_name="dossier",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="billing.invoice",
                        verbose_name="facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "frais",
                "verbose_name_plural": "frais",
                "ordering": ("-incurred_on", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="année")),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="dernier numéro"),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "séquence facture",
                "verbose_name_plural": "séquences factures",
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("description", models.CharField(max_length=500, verbose_name="description")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="début")),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="durée (minutes)",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="taux horaire",
                    ),
                ),
                ("is_billable", models.BooleanField(default=True, verbose_name="facturable")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="billing.invoice",
                        verbose_name="facture",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="matters.matter",
                        verbose_name="dossier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="intervenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "saisie de temps",
                "verbose_name_plural": "saisies de temps",
                "ordering": ("-started_at", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["cabinet", "status"], name="billing_inv_cabinet_status"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["cabinet", "client"], name="billing_inv_cabinet_client"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), models.Q(("number", ""), _negated=True)),
                fields=("cabinet", "number"),
                name="uniq_invoice_number_per_cabinet",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["cabinet", "matter"], name="billing_ex_cabinet_matter"),
        ),
        migrations.AddConstraint(
            model_name="invoicesequence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("cabinet", "year"),
                name="uniq_invoice_sequence_cabinet_year",
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["cabinet", "matter"], name="billing_te_cabinet_matter"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["cabinet", "user", "is_billable"], name="billing_te_user_bill"
            ),
        ),
    ]
