# Generated by Django 5.1.15 on 2026-08-05 01:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("matters", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("time", "Temps"), ("expense", "Débours"), ("other", "Autre")],
                        default="other",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("description", models.CharField(max_length=500, verbose_name="description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="prix unitaire HT",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="montant HT",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de facture",
                "verbose_name_plural": "lignes de facture",
                "ordering": ("created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ("-incurred_on", "-created_at"),
                "verbose_name": "débours",
                "verbose_name_plural": "débours",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicesequence",
            options={
                "verbose_name": "séquence de facture",
                "verbose_name_plural": "séquences de factures",
            },
        ),
        migrations.RemoveIndex(
            model_name="timeentry",
            name="billing_te_user_bill",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="billing_exp_cab_matter",
            old_name="billing_ex_cabinet_matter",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_cab_status",
            old_name="billing_inv_cabinet_status",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_cab_client",
            old_name="billing_inv_cabinet_client",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="billing_time_cab_matter",
            old_name="billing_te_cabinet_matter",
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="montant"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="incurred_on",
            field=models.DateField(verbose_name="date du frais"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Attribué à l'émission (FAC-YYYY-NNNNN).",
                max_length=32,
                verbose_name="numéro",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                max_digits=5,
                verbose_name="taux de TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="durée (minutes)"),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("250.00"),
                max_digits=10,
                verbose_name="taux horaire",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["cabinet", "invoice"], name="billing_exp_cab_invoice"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["cabinet", "user", "ended_at"], name="billing_time_cab_user"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["cabinet", "invoice"], name="billing_time_cab_invoice"),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="cabinet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.cabinet",
                verbose_name="cabinet",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="billing.invoice",
                verbose_name="facture",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="source_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="billing.expense",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="source_time_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="billing.timeentry",
            ),
        ),
    ]
