# Generated by Django 5.1.15 on 2026-08-18 15:44

import apps.core.money
from django.db import migrations, models


def switch_billing_to_usd(apps, schema_editor) -> None:
    Expense = apps.get_model("billing", "Expense")
    Invoice = apps.get_model("billing", "Invoice")
    Expense.objects.filter(currency="EUR").update(currency="USD")
    Invoice.objects.filter(currency="EUR").update(currency="USD")


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                default=apps.core.money.default_currency,
                max_length=3,
                verbose_name="devise",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                default=apps.core.money.default_currency,
                max_length=3,
                verbose_name="devise",
            ),
        ),
        migrations.RunPython(switch_billing_to_usd, migrations.RunPython.noop),
    ]
