# Generated by Django 5.1.15 on 2026-08-05 00:38

import apps.documents.models
import apps.documents.storage
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="Tags libres (ex. : contrat, pièce, correspondance).",
                        size=None,
                        verbose_name="tags",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="matters.matter",
                        verbose_name="dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="numéro de version")),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        storage=apps.documents.storage.PrivateDocumentStorage(),
                        upload_to=apps.documents.models.document_upload_to,
                        verbose_name="fichier",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="nom de fichier original"),
                ),
                (
                    "checksum",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="empreinte SHA-256"
                    ),
                ),
                ("size", models.PositiveBigIntegerField(default=0, verbose_name="taille (octets)")),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=127, verbose_name="type MIME"),
                ),
                (
                    "change_note",
                    models.CharField(blank=True, max_length=255, verbose_name="note de version"),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_document_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="téléversé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "version de document",
                "verbose_name_plural": "versions de document",
                "ordering": ("-version_number",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentversion",
                verbose_name="version courante",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["cabinet", "document"], name="documents_ver_cabinet_doc"),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("document", "version_number"),
                name="uniq_document_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["cabinet", "matter"], name="documents_doc_cabinet_matter"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["cabinet", "title"], name="documents_doc_cabinet_title"),
        ),
    ]
