# Generated by Django 5.1.15 on 2026-08-05 00:09

import apps.tenants.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=255, verbose_name="raison sociale"),
                ),
                ("siret", models.CharField(blank=True, max_length=14, verbose_name="SIRET")),
                ("vat_number", models.CharField(blank=True, max_length=32, verbose_name="n° TVA")),
                (
                    "bar_association",
                    models.CharField(blank=True, max_length=255, verbose_name="barreau"),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, verbose_name="adresse"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="complément d'adresse"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="code postal"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="ville")),
                ("country", models.CharField(default="FR", max_length=2, verbose_name="pays")),
                (
                    "default_currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="devise"),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=3650,
                        help_text="Durée RGPD de conservation des données (par défaut 10 ans).",
                        verbose_name="durée de conservation (jours)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "cabinet",
                "verbose_name_plural": "cabinets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, verbose_name="e-mail invité"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propriétaire"),
                            ("lawyer", "Avocat"),
                            ("associate", "Collaborateur"),
                            ("secretary", "Secrétaire"),
                            ("read_only", "Lecture seule"),
                        ],
                        default="associate",
                        max_length=32,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.tenants.models.generate_invitation_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="jeton",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.tenants.models.default_invitation_expiry,
                        verbose_name="expire le",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="acceptée le"),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CabinetPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("key", models.CharField(max_length=100, verbose_name="clé")),
                ("value", models.JSONField(blank=True, default=dict, verbose_name="valeur")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "préférence cabinet",
                "verbose_name_plural": "préférences cabinet",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("cabinet", "key"),
                        name="uniq_cabinet_preference_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propriétaire"),
                            ("lawyer", "Avocat"),
                            ("associate", "Collaborateur"),
                            ("secretary", "Secrétaire"),
                            ("read_only", "Lecture seule"),
                        ],
                        default="read_only",
                        max_length=32,
                        verbose_name="rôle",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "adhésion",
                "verbose_name_plural": "adhésions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="tenants_mem_user_id_7586b1_idx"
                    ),
                    models.Index(fields=["cabinet", "role"], name="tenants_mem_cabinet_923515_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("cabinet", "user"),
                        name="uniq_active_membership_cabinet_user",
                    )
                ],
            },
        ),
    ]
