# Generated by Django 5.1.15 on 2026-08-18 15:44

import apps.core.money
from django.db import migrations, models


def switch_cabinets_to_usd(apps, schema_editor) -> None:
    Cabinet = apps.get_model("tenants", "Cabinet")
    Cabinet.objects.filter(default_currency="EUR").update(default_currency="USD")


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabinet",
            name="default_currency",
            field=models.CharField(
                default=apps.core.money.default_currency,
                max_length=3,
                verbose_name="devise",
            ),
        ),
        migrations.RunPython(switch_cabinets_to_usd, migrations.RunPython.noop),
    ]
