# Generated by Django 5.1.15 on 2026-08-05 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hearing", "Audience"),
                            ("appointment", "Rendez-vous"),
                            ("deadline", "Délai de procédure"),
                            ("reminder", "Rappel"),
                        ],
                        db_index=True,
                        default="appointment",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("starts_at", models.DateTimeField(db_index=True, verbose_name="début")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                ("all_day", models.BooleanField(default=False, verbose_name="journée entière")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="lieu")),
                (
                    "remind_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date/heure d'envoi du rappel e-mail.",
                        null=True,
                        verbose_name="rappel le",
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="rappel envoyé le"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigné à",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="matters.matter",
                        verbose_name="dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement",
                "verbose_name_plural": "événements",
                "ordering": ("starts_at",),
                "indexes": [
                    models.Index(
                        fields=["cabinet", "starts_at"], name="calendar_ap_cabinet_7be077_idx"
                    ),
                    models.Index(
                        fields=["cabinet", "event_type", "starts_at"],
                        name="calendar_ap_cabinet_6708af_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("is_deleted", False), ("reminder_sent_at__isnull", True)
                        ),
                        fields=["remind_at"],
                        name="cal_event_remind_pending_idx",
                    ),
                ],
            },
        ),
    ]
