# Generated by Django 5.1.15 on 2026-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='terminé'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('hearing', 'Audience'), ('appointment', 'Rendez-vous'), ('deadline', 'Délai de procédure'), ('reminder', 'Rappel'), ('task', 'Tâche')], db_index=True, default='appointment', max_length=20, verbose_name='type'),
        ),
    ]
