# Generated by Django 5.1.15 on 2026-08-25 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_complete_crud'),
        ('matters', '0003_matter_is_archived'),
        ('tenants', '0002_currency_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='calendar_ap_cabinet_6708af_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='chamber',
            field=models.CharField(blank=True, max_length=128, verbose_name='chambre'),
        ),
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.CharField(blank=True, max_length=255, verbose_name='tribunal'),
        ),
        migrations.AddField(
            model_name='event',
            name='hearing_report',
            field=models.TextField(blank=True, verbose_name="compte-rendu d'audience"),
        ),
        migrations.AddField(
            model_name='event',
            name='hearing_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Planifiée'), ('held', 'Tenue'), ('postponed', 'Reportée'), ('cancelled', 'Annulée')], db_index=True, default='', max_length=20, verbose_name='statut audience'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='salle / lieu'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['cabinet', 'event_type', 'hearing_status', 'starts_at'], name='cal_event_hearing_status_idx'),
        ),
    ]
