# Generated by Django 5.1.15 on 2026-08-05 00:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("person", "Personne physique"), ("company", "Personne morale")],
                        db_index=True,
                        default="person",
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="prénom")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="nom")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date de naissance"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, verbose_name="raison sociale"),
                ),
                ("siret", models.CharField(blank=True, max_length=14, verbose_name="SIRET")),
                (
                    "legal_form",
                    models.CharField(blank=True, max_length=64, verbose_name="forme juridique"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="téléphone")),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, verbose_name="adresse"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="complément d'adresse"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="code postal"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="ville")),
                ("country", models.CharField(default="FR", max_length=2, verbose_name="pays")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="vecteur de recherche"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ("-updated_at",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="clients_client_search_gin"
                    ),
                    models.Index(
                        fields=["cabinet", "last_name", "first_name"],
                        name="clients_cli_cabinet_410376_idx",
                    ),
                    models.Index(
                        fields=["cabinet", "company_name"], name="clients_cli_cabinet_176387_idx"
                    ),
                ],
            },
        ),
    ]
