# Generated by Django 5.1.15 on 2026-08-05 00:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, verbose_name="référence"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="intitulé")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "practice_area",
                    models.CharField(blank=True, max_length=120, verbose_name="matière / domaine"),
                ),
                (
                    "jurisdiction",
                    models.CharField(blank=True, max_length=255, verbose_name="juridiction"),
                ),
                (
                    "opposing_party",
                    models.CharField(blank=True, max_length=255, verbose_name="partie adverse"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_progress", "En cours"),
                            ("on_hold", "En attente"),
                            ("closed", "Clos"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("opened_at", models.DateField(blank=True, null=True, verbose_name="ouvert le")),
                ("closed_at", models.DateField(blank=True, null=True, verbose_name="clos le")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="vecteur de recherche"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matters",
                        to="clients.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "responsible_lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_matters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="avocat responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "dossier",
                "verbose_name_plural": "dossiers",
                "ordering": ("-updated_at",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="matters_matter_search_gin"
                    ),
                    models.Index(
                        fields=["cabinet", "status"], name="matters_mat_cabinet_47255b_idx"
                    ),
                    models.Index(
                        fields=["cabinet", "practice_area"], name="matters_mat_cabinet_70da90_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("cabinet", "reference"),
                        name="uniq_matter_reference_per_cabinet",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatterSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="créé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="année")),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="dernier numéro"),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.cabinet",
                        verbose_name="cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "séquence dossier",
                "verbose_name_plural": "séquences dossiers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("cabinet", "year"),
                        name="uniq_matter_sequence_cabinet_year",
                    )
                ],
            },
        ),
    ]
